### ISSUE TITLE
table data json format

### ISSUE THREAD

**Issue by sannailtanen** [CityScope/CSL_Helsinki#6]
Is there a gama model that reads the table data in 'CityIO Data Structure Standard version 2.1' format?

**Comment by agrignard** [comment]
Dear @sannailtanen 

There is indeed  a generic GAMA model reading and writing to cityIO using the 2.1 format that can be found here
https://github.com/CityScope/CS_CityIO_Backend/tree/master/examples/GAMA/cityIO_Gama

**Comment by doorleyr** [comment]
I edited the code using @agrignard 's suggestion so now it can read from the Aalto table in the current format. However, the type numbers being sent by the Aalto table don't match what the simulation is looking for. So for now, the code is just reading from a sample json file which I saved as cityIO_Aalto.json. Once the scanner is sending the right data, we can change it back to reading the live table.
@sannailtanen can you look at the Gama code where citymatrix_map_settings is defined (line 48) and make sure that the data sent by the table is in line with this. You can change the data being sent to cityIO or the GAMA code or both.
Also, the position of the grid is still hardcoded in the wrong position. You need to change the constants "angle" and "center" in order to place the grid in whatever position you need.

**Comment by doorleyr** [comment]
Closing and creating new issues for the grid position and type inconsistency.

**Comment by agrignard** [comment]
"I edited the code using @agrignard 's suggestion so now it can read from the Aalto table in the current format. " @doorleyr would it be possible to point to the right commit in order to see and track what are the modification made?

I insist again on the genericity of the model developped in GAMA and raises a warning that this is very dangerous and not productive to duplicate the code of the CS_Simulation_GAMA or cityIO in this repo. The hole point of the CS_Simulation_GAMA or cityIOGama is to have a generic model that 1. can be used by other city (like you are doing) and 2. can be enhanced/improve modify by this city in order to improve the model itself. 

Right now the modification done are only benefical for Helsinki and doesn't benefit for the rest of the network.

@doorleyr how difficult would it be to integrate (first by asking in an issue and two proposing a pull request) those change in order to integrate it directly in the original model? I want to insist on this because it will be more and more difficult not to say impossible to keep the track on the 2 models.

**Comment by doorleyr** [comment]
The Aalto Gama model is now living in the CS_Simulation_GAMA repo so closing this issue.
