### ISSUE TITLE
Position of the grid is incorrect

### ISSUE THREAD

**Issue by doorleyr** [CityScope/CSL_Helsinki#7]
Currently, the position of the grid is hard-coded into the model. Eventually this should be solved in the main CS_GAMA_Simulation model as outlined in this issue: https://github.com/CityScope/CS_Simulation_GAMA/issues/37

For now, we can just hardcode the correct position of the grid. You need to change the constants "angle" and "center" in order to place the grid in whatever position you need.

**Comment by agrignard** [comment]
According to the table format the position and angle are already taken into account
see here https://github.com/CityScope/CS_CityIO_Backend/wiki/cityIO-Data-Structure#spatial-dictionary. So this value SHOULD'T be hard coded but we readden from the data sent. 

Again as mention in CityScope/CS_Simulation_GAMA#37 the model was developped before the 2.1 format so there is no way to get rotation and postion from the volpe grid whcih is still sending a 1.0 format. However it doesn't meand that we need to reproduce this.

Againin term of genericity, it would be better to modify the original model in order to have the possibility both to read this value form cityIO or hardcoded it if they are not available.

@doorleyr and or @sannailtanen in order to move forward would it be possible for you to had thos inofrmation in your grid/altoo.json?

**Comment by doorleyr** [comment]
The Aalto Gama model is now living in the CS_Simulation_GAMA repo so closing this issue.
